# Generated by Django 5.0.7 on 2024-10-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='advertencia_contenido',
            field=models.BooleanField(default=False, help_text='Indica si esta imagen debe mostrarse con una advertencia de contenido.', verbose_name='Advertencia de contenido'),
        ),
        migrations.AddField(
            model_name='foto',
            name='alt_descripcion',
            field=models.CharField(blank=True, help_text='Descripción alternativa para lectores de pantalla', max_length=255, verbose_name='Descripción alternativa'),
        ),
        migrations.AddField(
            model_name='foto',
            name='licencia',
            field=models.TextField(blank=True, help_text='Detalles sobre la licencia de imagen (ej. Creative Commons, Copyright, etc.)', verbose_name='Licencia'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción de la imagen', verbose_name='Descripción'),
        ),
    ]
