# Generated by Django 5.0.7 on 2024-11-10 14:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malbum', '0002_foto_advertencia_contenido_foto_alt_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='foto',
            name='colecciones',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='malbum.coleccion', verbose_name='Colecciones'),
        ),
        migrations.AddField(
            model_name='foto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='fotos', to='malbum.etiqueta', verbose_name='Etiquetas'),
        ),
    ]
