services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
      - media_volume:/code/media
      - static_volume:/code/staticfiles
      - ./certs:/etc/ssl/certs/malbum:ro
      - sqlite_data:/code/data
      - config_data:/code/config
      - ./keys:/code/keys
    environment:
      - PYTHONUNBUFFERED=1
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_RUN_DIR=/var/run/apache2
      - APACHE_LOG_DIR=/var/log/apache2
      - APACHE_LOCK_DIR=/var/lock/apache2
      - APACHE_PID_FILE=/var/run/apache2/apache2.pid
    depends_on:
      - volume-permissions

  volume-permissions:
    image: busybox
    volumes:
      - media_volume:/code/media
      - static_volume:/code/staticfiles
      - sqlite_data:/code/data
      - config_data:/code/config
      - ./keys:/code/keys
      - ./certs:/etc/ssl/certs/malbum
    command: >
      sh -c "chown -R 33:33 /code/media &&
             chown -R 33:33 /code/staticfiles &&
             chown -R 33:33 /code/data &&
             chown -R 33:33 /code/config &&
             chown -R 33:33 /code/keys &&
             chown -R 33:33 /etc/ssl/certs/malbum &&
             chmod -R 750 /etc/ssl/certs/malbum"

volumes:
  media_volume:
  static_volume:
  sqlite_data:
  config_data: