## Para usar este, correr `docker-compose -f docker-compose-prod.yml up`
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
      - ./entrypoint.sh:/code/entrypoint.sh
      - media_volume:/code/media