services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
      - media_volume:/code/media
      - static_volume:/code/staticfiles
      - ./certs:/etc/ssl/certs/malbum
      - sqlite_data:/code/data
      - config_data:/code/config
      - ./keys:/code/keys
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - volume-permissions

  volume-permissions:
    image: busybox
    volumes:
      - media_volume:/code/media
      - static_volume:/code/staticfiles
      - sqlite_data:/code/data
      - config_data:/code/config
      - ./keys:/code/keys
    command: >
      sh -c "chown -R 33:33 /code/media &&
             chown -R 33:33 /code/staticfiles &&
             chown -R 33:33 /code/data &&
             chown -R 33:33 /code/config &&
             chown -R 33:33 /code/keys"

volumes:
  media_volume:
  static_volume:
  sqlite_data:
  config_data: