version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
      - media_volume:/code/media
      - static_volume:/code/staticfiles
      - ./certs:/etc/ssl/certs/malbum
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  media_volume:
  static_volume: