## Para usar este, correr `docker-compose -f docker-compose-prod.yml up`
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./media:/code/media
      - ./staticfiles:/code/staticfiles
      - ./config:/code/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CONFIG_DIR=/code/config

volumes:
  media_volume: