# Generated by Django 5.0.7 on 2024-12-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='activitypub_id',
            field=models.URLField(blank=True, help_text='The unique ID for ActivityPub federation.', unique=True),
        ),
    ]
