# Generated by Django 5.0.7 on 2024-12-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuario_activitypub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
    ]
