# Generated by Django 5.0.7 on 2025-01-02 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_follow_unique_together_follow_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='remote_domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='follow',
            name='remote_username',
            field=models.CharField(max_length=255),
        ),
    ]
