# Generated by Django 5.0.7 on 2025-01-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_alter_follow_unique_together_alter_follow_following_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_id', models.URLField(unique=True)),
                ('actor_url', models.URLField()),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('published', models.DateTimeField()),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='remote_photos/')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
