# Generated by Django 5.0.7 on 2025-01-10 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_remotepost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotepost',
            options={},
        ),
        migrations.AddField(
            model_name='remotepost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='actor_url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='remote_images/'),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='remotepost',
            name='remote_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
