# Generated by Django 5.0.7 on 2025-01-10 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_remotepost_options_remotepost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotepost',
            options={'ordering': ['-published']},
        ),
    ]
