# Generated by Django 5.0.7 on 2025-01-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_alter_remotepost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='remote_domain',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='remote_username',
        ),
        migrations.AlterField(
            model_name='follow',
            name='actor_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
